# Generated by Django 3.0.5 on 2020-06-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(),
        ),
    ]
