# Generated by Django 3.0.5 on 2020-06-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200629_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.CharField(max_length=100),
        ),
    ]
