# Generated by Django 3.0.5 on 2020-06-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20200618_0402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Framework',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
