# Generated by Django 3.0.5 on 2020-07-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_group_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
